version: '3.7'
networks:
  internal-network:
    name: ${CONTEXT_NAME}_network
services:
  swsite_dev:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/dev/Dockerfile
    container_name: ${CONTEXT_NAME}_swsite_dev
    restart: always
    user: "${UID}:${GID}"
    environment:
      - USER_UID=${UID}
      - USER_GID=${GID}
    volumes:
      - "${PWD}/webapp:/webapp"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swsite_dev.entrypoints=web"
      - "traefik.http.routers.swsite_dev.rule=Host(`$DEV_HOST`)"
      - "traefik.http.services.swsite_dev.loadbalancer.server.port=3000"
    networks:
      - internal-network
