version: '3.7'
networks:
  internal-network:
    name: ${CONTEXT_NAME}_network
services:
  swsite:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/prod/Dockerfile
    container_name: ${CONTEXT_NAME}_swsite
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swsite.entrypoints=web"
      - "traefik.http.routers.swsite.rule=Host(`$PROD_HOST`)"
      - "traefik.http.services.swsite.loadbalancer.server.port=3000"
    networks:
      - internal-network
