version: '3.7'
networks:
  internal-network:
    name: ${CONTEXT_NAME}_network
services:
  myapp:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/prod/Dockerfile
    container_name: ${CONTEXT_NAME}_myapp
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SERVER_HOST=${PROD_SERVER_HOST}
      - SERVER_PORT=${INTERNAL_SERVER_PORT}
      - CLIENT_HOST=${PROD_CLIENT_HOST}
      - CLIENT_PORT=${INTERNAL_CLIENT_PORT}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      # Configuration of multiple domains mappend to different ports 
      # in one container: https://community.traefik.io/t/docker-container-with-multiple-ports/4657/2
      # ------
      # Server App
      - "traefik.http.routers.myapp_dev_server.entrypoints=web"
      - "traefik.http.routers.myapp_dev_server.rule=Host(`$PROD_SERVER_HOST`)"
      - "traefik.http.routers.myapp_dev_server.service=myapp_dev_server_service"
      - "traefik.http.services.myapp_dev_server_service.loadbalancer.server.port=$INTERNAL_SERVER_PORT"
      # ------
      # Client App
      - "traefik.http.routers.myapp_dev_client.entrypoints=web"
      - "traefik.http.routers.myapp_dev_client.rule=Host(`$PROD_CLIENT_HOST`)"
      - "traefik.http.routers.myapp_dev_client.service=myapp_dev_client_service"
      - "traefik.http.services.myapp_dev_client_service.loadbalancer.server.port=$INTERNAL_CLIENT_PORT"
    networks:
      - internal-network
