version: "3.7"
networks:
  internal-network:
    name: ${CONTEXT_NAME}_network
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=$TRAEFIK_DEBUG"
      - "--providers.docker=true"
      - "--log.LEVEL=DEBUG"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.traefik.address=:8282" #dashboard default port 8080
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.lets-encr.acme.httpchallenge=true"
      - "--certificatesresolvers.lets-encr.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.lets-encr.acme.email=$CONTEXT_EMAIL"
      - "--certificatesresolvers.lets-encr.acme.storage=/letsencrypt/acme.json"
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    volumes:
      - "$CONTEXT_DIR/data-traefic/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_HOST}`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8282"
     # - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$WRzy2Xaq$0.AK7l1NoBYAc1LhAHoYc."
     # - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
     # - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
     # - "traefik.http.routers.traefik-secure.entrypoints=https"
     # - "traefik.http.routers.traefik-secure.rule=Host(`traefik.localhost`)"
     # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
     # - "traefik.http.routers.traefik-secure.tls=true"
     # - "traefik.http.routers.traefik-secure.tls.certresolver=lets-encr"
     # - "traefik.http.routers.traefik-secure.service=api@internal"
    networks:
      - internal-network




